name: Uplaod Files

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
                uses: actions/checkout@v2

            - name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.12' # Replace with the desired Python version

            - name: Install dependencies
                run: pip install -r requirements.txt

            - name: Run main.py
                run: python main.py